.PHONY:clean
all:main.o  admin.o students.o books_func.o students_func.o admin_func.o
	g++ -std=c++11 -Wall  -o all main.cpp admin.cpp  students.cpp books_func.cpp students_func.cpp admin_func.cpp
clean:
	rm main.o  admin.o students.o books_func.o students_func.o admin_func.o all
